language: node_js

node_js:
  - "8"

branches:
  only:
  - publish

cache:
  directories:
    - node_modules


before_install:

- openssl aes-256-cbc -K $encrypted_9d4fd0d459b1_key -iv $encrypted_9d4fd0d459b1_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d


- chmod 600 ~/.ssh/id_rsa 

- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config

- git config --global user.name 'prettydog'
- git config --global user.email 'prettydoge@yahoo.com'


install:
- npm install hexo-cli -g
- npm install

script:
- npm run deploy  # hexo clean && hexo g -d
